/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/cache-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cacheCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/service/objects/{object_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 오브제 조회
         * @description 오브제를 조회합니다.
         */
        get: operations["getObject"];
        /**
         * 오브제 수정
         * @description 오브제 정보를 수정합니다. 빈칸으로 두면 해당 필드는 업데이트하지 않습니다.
         */
        put: operations["updateObject"];
        post?: never;
        /**
         * 오브제 삭제
         * @description 오브제를 소프트 삭제합니다.
         */
        delete: operations["deleteObject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/service/objects/{object_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 오브제 로그 전송
         * @description 오브제의 로그를 전송합니다.
         */
        post: operations["createObjectLog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/service/objects/{object_id}/power": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 오브제 전원 상태 SSE 이벤트 소스 생성
         * @description 오브제의 전원 상태 변경 이벤트를 수신하기 위한 SSE 이벤트 소스를 생성
         */
        get: operations["createPowerEventSource"];
        put?: never;
        /**
         * 오브제 전원 상태 제어
         * @description 오브제의 전원 상태를 변경합니다. ON 또는 OFF로 설정할 수 있습니다.
         */
        post: operations["controlPower"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/service/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 매장 목록 조회
         * @description 매장에 등록된 매장 목록을 조회합니다.
         */
        get: operations["findStoreList"];
        put?: never;
        /**
         * 매장 등록
         * @description 매장 정보를 등록합니다.
         */
        post: operations["createStore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/service/stores/send-event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 제어 이벤트 전송 */
        post: operations["sendEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/service/stores/{store_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 매장 단건 조회
         * @description 매장 ID를 통해 매장 정보를 조회합니다.
         */
        get: operations["getStore"];
        /**
         * 매장 정보 수정
         * @description 매장 ID를 통해 매장 정보를 수정합니다. 빈칸이면 수정되지 않습니다.
         */
        put: operations["updateStore"];
        post?: never;
        /**
         * 매장 삭제
         * @description 매장 ID를 통해 매장을 삭제합니다.
         */
        delete: operations["deleteStore"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/service/stores/{store_id}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 매장 상세 정보 조회
         * @description 매장 ID를 통해 매장의 상세 정보를 조회합니다. PC 목록과 각 PC에 속한 오브제 목록을 포함합니다.
         */
        get: operations["getStoreDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/service/stores/{store_id}/pcs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 매장별 PC 목록 조회
         * @description 특정 매장에 등록된 모든 PC 목록을 조회합니다.
         */
        get: operations["getPcsByStoreId"];
        put?: never;
        /**
         * PC 등록
         * @description 매장에 PC를 등록합니다.
         */
        post: operations["createPc"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/service/stores/{store_id}/pcs/{pc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * PC 단건 조회
         * @description 특정 PC의 정보를 조회합니다.
         */
        get: operations["getPcItem"];
        /**
         * PC 정보 수정
         * @description PC의 정보를 수정합니다. PC 이름과 SW 버전을 변경할 수 있습니다.
         */
        put: operations["updatePcInformation"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/service/stores/{store_id}/pcs/{pc_id}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * PC 헬스 체크 SSE 이벤트 소스 생성
         * @description PC의 상태를 실시간으로 모니터링하기 위한 SSE 이벤트 소스를 생성합니다.
         */
        get: operations["createPcHealthCheckEventSource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/service/stores/{store_id}/pcs/{pc_id}/objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * PC에 등록된 오브제 목록 조회
         * @description 특정 매장의 특정 PC에 등록된 모든 오브제 목록을 조회합니다.
         */
        get: operations["getObjectsByPc"];
        put?: never;
        /**
         * 오브제 등록
         * @description 새로운 오브제를 등록합니다.
         */
        post: operations["createObject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/service/stores/{store_id}/{pc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * PC 삭제
         * @description PC를 삭제합니다.
         */
        delete: operations["deletePc"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        StoreOperateTimeDto: {
            /**
             * @description 요일
             * @example MON
             * @enum {string}
             */
            day_of_week: "MON" | "TUE" | "WED" | "THU" | "FRI" | "SAT" | "SUN";
            /**
             * @description 운영 시작 시간
             * @example 09:00
             */
            open_time: string;
            /**
             * @description 운영 종료 시간
             * @example 18:00
             */
            close_time: string;
        };
        StoreUpdateRequest: {
            /**
             * @description 매장명
             * @example GM_하우스_도산
             */
            store_name?: string;
            /**
             * @description 국가 코드
             * @example KR
             */
            country_code?: string;
            /**
             * @description 매장주소
             * @example 서울시 강남구 압구정로 46길 50
             */
            address?: string;
            /**
             * Format: double
             * @description 위도
             * @example 37.5253221
             */
            latitude?: number;
            /**
             * Format: double
             * @description 경도
             * @example 127.0356785
             */
            longitude?: number;
            /**
             * @description 타임존
             * @example Asia/Seoul
             */
            timezone?: string;
            /**
             * @description 매장 운영 시간 (모든 요일 MON, TUE, WED, THU, FRI, SAT, SUN이 포함되어야 함)
             * @example [
             *       {
             *         "day_of_week": "MON",
             *         "open_time": "09:00",
             *         "close_time": "18:00"
             *       },
             *       {
             *         "day_of_week": "TUE",
             *         "open_time": "09:00",
             *         "close_time": "18:00"
             *       },
             *       {
             *         "day_of_week": "WED",
             *         "open_time": "09:00",
             *         "close_time": "18:00"
             *       },
             *       {
             *         "day_of_week": "THU",
             *         "open_time": "09:00",
             *         "close_time": "18:00"
             *       },
             *       {
             *         "day_of_week": "FRI",
             *         "open_time": "09:00",
             *         "close_time": "18:00"
             *       },
             *       {
             *         "day_of_week": "SAT",
             *         "open_time": "09:00",
             *         "close_time": "18:00"
             *       },
             *       {
             *         "day_of_week": "SUN",
             *         "open_time": "09:00",
             *         "close_time": "18:00"
             *       }
             *     ]
             */
            operate_times?: components["schemas"]["StoreOperateTimeDto"][];
        };
        StoreUpdateResponse: {
            /** @description 매장 ID */
            store_id: string;
            /** @description 매장 이름 */
            store_name: string;
            /**
             * Format: date-time
             * @description 수정 시간
             */
            modified_at: string;
        };
        PcUpdateRequest: {
            /**
             * @description 변경하고자 하는 PC Name을 입력하세요. 빈칸으로 두면 PC Name은 업데이트하지 않습니다.
             * @example PC001
             */
            pc_name?: string;
            /**
             * @description 변경하고자 하는 SW Version을 입력하세요. 빈칸으로 두면 SW Version은 업데이트하지 않습니다.
             * @example 10.0v
             */
            sw_version?: string;
        };
        PcUpdateResponse: {
            store_id: string;
            pc_id: string;
            /** Format: date-time */
            modified_at: string;
        };
        FirmwareVersionUpdateDto: {
            /**
             * @description 보드 ID
             * @example 1-1
             */
            board_id?: string;
            /**
             * @description 보드 타입
             * @example MAI
             */
            board_type?: string;
            /**
             * @description 버전
             * @example 0.1.51
             */
            version?: string;
        };
        ObjectOperationTimeUpdateDto: {
            /**
             * @description 시작 시간
             * @example 09:00
             */
            start_time?: string;
            /**
             * @description 종료 시간
             * @example 22:00
             */
            end_time?: string;
        };
        ObjectUpdateRequest: {
            /**
             * @description 변경하고자 하는 오브제 이름. 빈칸으로 두면 오브제 이름은 업데이트하지 않습니다.
             * @example Robot1
             */
            object_name?: string;
            /** @description 변경하고자 하는 오브제 동작 시간. 빈칸으로 두면 동작 시간은 업데이트하지 않습니다. */
            object_operation_time?: components["schemas"]["ObjectOperationTimeUpdateDto"];
            /**
             * @description 변경하고자 하는 스케줄 플래그. 빈칸으로 두면 스케줄 플래그는 업데이트하지 않습니다.
             * @example true
             * @enum {boolean}
             */
            schedule_flag?: "true" | "false";
            /** @description 변경하고자 하는 펌웨어 버전. 빈칸으로 두면 펌웨어 버전은 업데이트하지 않습니다. */
            firmware_version?: components["schemas"]["FirmwareVersionUpdateDto"];
            /**
             * @description 변경하고자 하는 동작 상태. 빈칸으로 두면 동작 상태는 업데이트하지 않습니다.
             * @example PLAY
             * @enum {string}
             */
            operation_status?: "PLAY" | "STOP" | "REPEAT";
        };
        ObjectUpdateResponse: {
            /**
             * @description 오브제 ID
             * @example 0KPX4RM5GZWT0
             */
            object_id: string;
            /**
             * Format: date-time
             * @description 수정 시간
             * @example 2025-05-15T00:00:00Z
             */
            modified_at: string;
        };
        StoreCreateRequest: {
            /**
             * @description 매장명
             * @example GM_하우스_도산
             */
            store_name: string;
            /**
             * @description 국가 코드
             * @example KR
             */
            country_code: string;
            /**
             * @description 매장주소
             * @example 서울시 강남구 압구정로 46길 50
             */
            address: string;
            /**
             * Format: double
             * @description 위도
             * @example 37.5253221
             */
            latitude: number;
            /**
             * Format: double
             * @description 경도
             * @example 127.0356785
             */
            longitude: number;
            /**
             * @description 타임존
             * @example Asia/Seoul
             */
            timezone: string;
            /**
             * @description 매장 운영 시간
             * @example [
             *       {
             *         "day_of_week": "MON",
             *         "open_time": "09:00",
             *         "close_time": "18:00"
             *       },
             *       {
             *         "day_of_week": "TUE",
             *         "open_time": "09:00",
             *         "close_time": "18:00"
             *       },
             *       {
             *         "day_of_week": "WED",
             *         "open_time": "09:00",
             *         "close_time": "18:00"
             *       },
             *       {
             *         "day_of_week": "THU",
             *         "open_time": "09:00",
             *         "close_time": "18:00"
             *       },
             *       {
             *         "day_of_week": "FRI",
             *         "open_time": "09:00",
             *         "close_time": "19:00"
             *       },
             *       {
             *         "day_of_week": "SAT",
             *         "open_time": "09:00",
             *         "close_time": "19:00"
             *       },
             *       {
             *         "day_of_week": "SUN",
             *         "open_time": "09:00",
             *         "close_time": "19:00"
             *       }
             *     ]
             */
            operate_times: components["schemas"]["StoreOperateTimeDto"][];
        };
        StoreCreateResponse: {
            /** @description 매장 ID */
            id: string;
            /** @description 매장 이름 */
            store_name: string;
            /**
             * Format: date-time
             * @description 생성 시간
             */
            created_at: string;
        };
        PcCreateRequest: {
            /**
             * @description PC Name
             * @example PC001
             */
            pc_name: string;
            /**
             * @description SW Version
             * @example 10
             */
            sw_version: string;
        };
        PcAddResponse: {
            store_id: string;
            pc_id: string;
            /** Format: date-time */
            created_at: string;
        };
        FirmwareVersionDto: {
            /**
             * @description Board Id
             * @example 1-1
             */
            board_id: string;
            /**
             * @description Board Type
             * @example MAI
             */
            board_type: string;
            /**
             * @description Version
             * @example 0.1.51
             */
            version: string;
        };
        ObjectAddRequest: {
            /**
             * @description Object Name
             * @example Robot1
             */
            object_name: string;
            /** @description Object Operation Time */
            object_operation_time: components["schemas"]["ObjectOperationTimeDto"];
            /**
             * @description Schedule Flag
             * @example true
             * @enum {boolean}
             */
            schedule_flag: "true" | "false";
            /** @description Firmware Version */
            firmware_version: components["schemas"]["FirmwareVersionDto"];
            /**
             * @description Operation Status
             * @example PLAY
             * @enum {string}
             */
            operation_status: "PLAY" | "STOP" | "REPEAT";
        };
        ObjectOperationTimeDto: {
            /**
             * @description Start Time
             * @example 09:00
             */
            start_time: string;
            /**
             * @description End Time
             * @example 22:00
             */
            end_time: string;
        };
        ObjectCreateResponse: {
            object_id: string;
            /** Format: date-time */
            created_at: string;
        };
        StoreEventSendRequestDTO: {
            storeId?: string;
            pcId?: string;
            objectId?: string;
            /** @enum {string} */
            event?: "ON" | "OFF" | "REBOOT";
        };
        /** @description 오브제 전원 제어 요청 */
        ObjectPowerControlRequest: {
            /**
             * @description 전원 상태
             * @example ON
             * @enum {string}
             */
            power_status: "ON" | "OFF";
        };
        ErrorDataDto: {
            /**
             * @description Board ID
             * @example 1-1
             */
            boardId?: string;
            /**
             * @description Board Type
             * @example MAI
             */
            boardType?: string;
            /**
             * @description Error Code
             * @example 16
             */
            errorCode?: string;
        };
        ObjectLogRequest: {
            /**
             * @description Power Status
             * @example ON
             * @enum {string}
             */
            power_status: "ON" | "OFF";
            /**
             * @description Operation Status
             * @example PLAY
             * @enum {string}
             */
            operation_status: "PLAY" | "STOP" | "REPEAT";
            /** @description Power Consumption */
            power_consumption?: components["schemas"]["PowerConsumptionDto"];
            /** @description Error Data */
            error_data?: components["schemas"]["ErrorDataDto"][];
        };
        PowerConsumptionDto: {
            /**
             * @description Volt
             * @example 220V
             */
            volt?: string;
            /**
             * @description Ampere
             * @example 10A
             */
            ampere?: string;
            /**
             * @description Watt
             * @example 2200W
             */
            watt?: string;
        };
        ObjectLogResponse: {
            /**
             * @description Object ID
             * @example 0KQA3CVKAEFST
             */
            object_id: string;
            /**
             * Format: date-time
             * @description Created At
             * @example 2023-04-29T06:20:05.916692Z
             */
            created_at: string;
        };
        StoreListResponse: {
            /** @description Store List */
            stores: components["schemas"]["StoreResponse"][];
        };
        StoreResponse: {
            /**
             * @description Store ID
             * @example 0KPW9SYR11DF6
             */
            id: string;
            /**
             * @description Store Name
             * @example Store 1
             */
            store_name: string;
            /**
             * @description Country Code
             * @example KR
             */
            country_code: string;
            /**
             * @description Address
             * @example 123
             */
            address?: string;
            /**
             * Format: double
             * @description Latitude
             * @example 37.5665
             */
            latitude?: number;
            /**
             * Format: double
             * @description Longitude
             * @example 126.978
             */
            longitude?: number;
            /**
             * @description Timezone
             * @example Asia/Seoul
             */
            timezone?: string;
            /** @description Store Operation Times */
            operate_times?: components["schemas"]["StoreOperateTimeDto"][];
            /**
             * Format: date-time
             * @description Created At
             * @example 2023-01-01T00:00:00Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @description Modified At
             * @example 2023-01-01T00:00:00Z
             */
            modified_at: string;
        };
        PcListResponse: {
            pcs: components["schemas"]["PcResponse"][];
        };
        PcResponse: {
            store_id: string;
            pc_id: string;
            pc_name: string;
            sw_version: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            modified_at?: string;
            created_by?: string;
            modified_by?: string;
        };
        ErrorData: {
            /**
             * @description Board ID
             * @example 1-1
             */
            boardId: string;
            /**
             * @description Board Type
             * @example MAI
             */
            boardType: string;
            /**
             * @description Error Code
             * @example 16
             */
            errorCode: string;
        };
        ObjectResponse: {
            id: string;
            object_name: string;
            /** @enum {string} */
            operation_status: "PLAY" | "STOP" | "REPEAT";
            schedule_flag: boolean;
            /** @enum {string} */
            power_status?: "ON" | "OFF";
            power_consumption?: components["schemas"]["PowerConsumption"];
            error_data?: components["schemas"]["ErrorData"][];
            /** Format: date-time */
            modified_at?: string;
            timezone?: string;
        };
        PowerConsumption: {
            /**
             * @description Volt
             * @example 220V
             */
            volt: string;
            /**
             * @description Ampere
             * @example 10A
             */
            ampere: string;
            /**
             * @description Watt
             * @example 2200W
             */
            watt: string;
        };
        PcWithObjects: {
            pc_id: string;
            pc_name: string;
            sw_version: string;
            objects: components["schemas"]["ObjectResponse"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            modified_at?: string;
        };
        StoreDetailResponse: {
            store_id: string;
            store_name: string;
            country_code: string;
            address?: string;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
            timezone: string;
            operate_times: components["schemas"]["StoreOperateTimeDto"][];
            pcs: components["schemas"]["PcWithObjects"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            modified_at?: string;
        };
        ObjectStatusResponse: {
            /**
             * @description Object ID
             * @example 0KPX4RM5GZWT0
             */
            id: string;
            /**
             * @description Object Name
             * @example Robot 1
             */
            object_name: string;
            /** @description Status Details */
            status_details: components["schemas"]["StatusDetails"];
            /**
             * Format: date-time
             * @description 생성일
             * @example 2025-05-15T06:37:17.367995Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @description 수정일
             * @example 2025-05-15T06:37:17.367995Z
             */
            modified_at: string;
            /**
             * @description Store Timezone
             * @example Asia/Seoul
             */
            timezone?: string;
        };
        StatusDetails: {
            /**
             * @description Power Status
             * @example ON
             * @enum {string}
             */
            power_status: "ON" | "OFF";
            /**
             * @description Operation Status
             * @example PLAY
             * @enum {string}
             */
            operation_status: "PLAY" | "STOP" | "REPEAT";
            /** @description Power Consumption */
            power_consumption?: components["schemas"]["PowerConsumption"];
            /** @description Error Data */
            error_data?: components["schemas"]["ErrorData"][];
            /**
             * Format: date-time
             * @description Snapshot Modified Date
             */
            modified_at?: string;
        };
        SseEmitter: {
            /** Format: int64 */
            timeout?: number;
        };
        StoreDeleteResponse: {
            /** @description 매장 ID */
            store_id: string;
            /** @description 매장 이름 */
            store_name: string;
            /**
             * Format: date-time
             * @description 삭제 시간
             */
            deleted_at: string;
        };
        PcDeleteResponse: {
            /** @description 매장 ID */
            store_id: string;
            /** @description PC ID */
            pc_id: string;
            /** @description PC 이름 */
            pc_name: string;
            /**
             * Format: date-time
             * @description 삭제 시간
             */
            deleted_at: string;
        };
        ObjectDeleteResponse: {
            /** @description 오브제 ID */
            object_id: string;
            /** @description 오브제 이름 */
            object_name: string;
            /**
             * Format: date-time
             * @description 삭제 시간
             */
            deleted_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    cacheCheck: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Bearer Authentication 토큰 (USER 권한 요청 시 필수)
                 * @example Bearer ...
                 */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Bearer Authentication 토큰 (USER 권한 요청 시 필수)
                 * @example Bearer ...
                 */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    getObject: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Bearer Authentication 토큰 (USER 권한 요청 시 필수)
                 * @example Bearer ...
                 */
                Authorization?: string;
            };
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ObjectStatusResponse"];
                };
            };
        };
    };
    updateObject: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Bearer Authentication 토큰 (USER 권한 요청 시 필수)
                 * @example Bearer ...
                 */
                Authorization?: string;
            };
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObjectUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ObjectUpdateResponse"];
                };
            };
        };
    };
    deleteObject: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Bearer Authentication 토큰 (USER 권한 요청 시 필수)
                 * @example Bearer ...
                 */
                Authorization?: string;
            };
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ObjectDeleteResponse"];
                };
            };
        };
    };
    createObjectLog: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Bearer Authentication 토큰 (USER 권한 요청 시 필수)
                 * @example Bearer ...
                 */
                Authorization?: string;
            };
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObjectLogRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ObjectLogResponse"];
                };
            };
        };
    };
    createPowerEventSource: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string;
                /**
                 * @description Bearer Authentication 토큰 (USER 권한 요청 시 필수)
                 * @example Bearer ...
                 */
                Authorization?: string;
            };
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SseEmitter"];
                };
            };
        };
    };
    controlPower: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Bearer Authentication 토큰 (USER 권한 요청 시 필수)
                 * @example Bearer ...
                 */
                Authorization?: string;
            };
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObjectPowerControlRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    findStoreList: {
        parameters: {
            query: {
                country_code: string;
            };
            header?: {
                /**
                 * @description Bearer Authentication 토큰 (USER 권한 요청 시 필수)
                 * @example Bearer ...
                 */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StoreListResponse"];
                };
            };
        };
    };
    createStore: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Bearer Authentication 토큰 (USER 권한 요청 시 필수)
                 * @example Bearer ...
                 */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StoreCreateResponse"];
                };
            };
        };
    };
    sendEvent: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Bearer Authentication 토큰 (USER 권한 요청 시 필수)
                 * @example Bearer ...
                 */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreEventSendRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getStore: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Bearer Authentication 토큰 (USER 권한 요청 시 필수)
                 * @example Bearer ...
                 */
                Authorization?: string;
            };
            path: {
                store_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StoreResponse"];
                };
            };
        };
    };
    updateStore: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Bearer Authentication 토큰 (USER 권한 요청 시 필수)
                 * @example Bearer ...
                 */
                Authorization?: string;
            };
            path: {
                store_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StoreUpdateResponse"];
                };
            };
        };
    };
    deleteStore: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Bearer Authentication 토큰 (USER 권한 요청 시 필수)
                 * @example Bearer ...
                 */
                Authorization?: string;
            };
            path: {
                store_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StoreDeleteResponse"];
                };
            };
        };
    };
    getStoreDetail: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Bearer Authentication 토큰 (USER 권한 요청 시 필수)
                 * @example Bearer ...
                 */
                Authorization?: string;
            };
            path: {
                store_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StoreDetailResponse"];
                };
            };
        };
    };
    getPcsByStoreId: {
        parameters: {
            query: {
                store_id: string;
            };
            header?: {
                /**
                 * @description Bearer Authentication 토큰 (USER 권한 요청 시 필수)
                 * @example Bearer ...
                 */
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PcListResponse"];
                };
            };
        };
    };
    createPc: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Bearer Authentication 토큰 (USER 권한 요청 시 필수)
                 * @example Bearer ...
                 */
                Authorization?: string;
            };
            path: {
                store_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PcCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PcAddResponse"];
                };
            };
        };
    };
    getPcItem: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Bearer Authentication 토큰 (USER 권한 요청 시 필수)
                 * @example Bearer ...
                 */
                Authorization?: string;
            };
            path: {
                pc_id: string;
                store_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PcResponse"];
                };
            };
        };
    };
    updatePcInformation: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Bearer Authentication 토큰 (USER 권한 요청 시 필수)
                 * @example Bearer ...
                 */
                Authorization?: string;
            };
            path: {
                pc_id: string;
                store_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PcUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PcUpdateResponse"];
                };
            };
        };
    };
    createPcHealthCheckEventSource: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string;
                /**
                 * @description Bearer Authentication 토큰 (USER 권한 요청 시 필수)
                 * @example Bearer ...
                 */
                Authorization?: string;
            };
            path: {
                pc_id: string;
                store_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE 이벤트 소스 생성 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
        };
    };
    getObjectsByPc: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Bearer Authentication 토큰 (USER 권한 요청 시 필수)
                 * @example Bearer ...
                 */
                Authorization?: string;
            };
            path: {
                store_id: string;
                pc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ObjectResponse"][];
                };
            };
        };
    };
    createObject: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Bearer Authentication 토큰 (USER 권한 요청 시 필수)
                 * @example Bearer ...
                 */
                Authorization?: string;
            };
            path: {
                store_id: string;
                pc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObjectAddRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ObjectCreateResponse"];
                };
            };
        };
    };
    deletePc: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Bearer Authentication 토큰 (USER 권한 요청 시 필수)
                 * @example Bearer ...
                 */
                Authorization?: string;
            };
            path: {
                pc_id: string;
                store_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PcDeleteResponse"];
                };
            };
        };
    };
}
